# TCL File Generated by Component Editor 11.0sp1
# Sun Mar 11 14:17:03 GMT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | keypad_controller "keypad_controller" v1.0
# | Pete Hemery 2012.03.11.14:17:03
# | Modified Keypad.vhd provided by Nigel to include latch signal
# | 
# | /home/netlab/prhemery/Altera_Systems_Labs/De0_Counter/ip/keypad_controller/keypad_controller.vhd
# | 
# |    ./keypad_controller.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module keypad_controller
# | 
set_module_property DESCRIPTION "Modified Keypad.vhd provided by Nigel to include latch signal"
set_module_property NAME keypad_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Peripherals/Microcontroller Peripherals"
set_module_property AUTHOR "Pete Hemery"
set_module_property DISPLAY_NAME keypad_controller
set_module_property TOP_LEVEL_HDL_FILE keypad_controller.vhd
set_module_property TOP_LEVEL_HDL_MODULE keypad_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME keypad_controller
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file keypad_controller.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point keypad_controller_slave
# | 
add_interface keypad_controller_slave avalon end
set_interface_property keypad_controller_slave addressAlignment DYNAMIC
set_interface_property keypad_controller_slave addressUnits WORDS
set_interface_property keypad_controller_slave associatedClock clk
set_interface_property keypad_controller_slave burstOnBurstBoundariesOnly false
set_interface_property keypad_controller_slave explicitAddressSpan 0
set_interface_property keypad_controller_slave holdTime 0
set_interface_property keypad_controller_slave isMemoryDevice false
set_interface_property keypad_controller_slave isNonVolatileStorage false
set_interface_property keypad_controller_slave linewrapBursts false
set_interface_property keypad_controller_slave maximumPendingReadTransactions 0
set_interface_property keypad_controller_slave printableDevice false
set_interface_property keypad_controller_slave readLatency 0
set_interface_property keypad_controller_slave readWaitTime 1
set_interface_property keypad_controller_slave setupTime 0
set_interface_property keypad_controller_slave timingUnits Cycles
set_interface_property keypad_controller_slave writeWaitTime 0

set_interface_property keypad_controller_slave ENABLED true

add_interface_port keypad_controller_slave shift readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 0

set_interface_property clk ENABLED true

add_interface_port clk sys_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_n
# | 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT

set_interface_property reset_n ENABLED true

add_interface_port reset_n resetn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rows
# | 
add_interface rows conduit end

set_interface_property rows ENABLED true

add_interface_port rows row export Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point columns
# | 
add_interface columns conduit end

set_interface_property columns ENABLED true

add_interface_port columns col export Output 4
# | 
# +-----------------------------------
